bitcoin: true
ethereum: true
ripple: true
litecoin: true
bitcoincash: false
digibyte: true
dash: true
cardano: true
iota: true
nem: true
vertcoin: true
myriad: true
neo: true
tezos: true
decred: true
siacoin: true
ardor: false
dogecoin: false
ethereumclassic: false
monero: false
nano: false
qtum: false
ripple: false
stellar: false
zcash: false
zencash: false
